app.controller('class',function($scope){
    $(window).scrollTop(0);
    //分页器事件
    $(".page").createPage({
        pageCount:10,
        current:1,
        backFn:function(p){
        }
    });
    $scope.listNav = {
        first:"谷物"
    }
    $scope.guwuList = [
        {
            src:"img/dadou.png",
            p:"大豆1000g",
            span:"99.00"
        },
        {
            src:"img/yumi.png",
            p:"玉米500g",
            span:"68.00"
        },
        {
            src:"img/xiaomai.png",
            p:"小麦500g",
            span:"46.00"
        },
        {
            src:"img/dami1.png",
            p:"大米400g",
            span:"29.00"
        },
        {
            src:"img/xiaomi.png",
            p:"小米500g",
            span:"28.00"
        },
        {
            src:"img/dadou.png",
            p:"大豆1000g",
            span:"99.00"
        },
        {
            src:"img/yumi.png",
            p:"玉米500g",
            span:"68.00"
        },
        {
            src:"img/xiaomai.png",
            p:"小麦500g",
            span:"46.00"
        },
        {
            src:"img/dami1.png",
            p:"大米400g",
            span:"29.00"
        },
        {
            src:"img/xiaomi.png",
            p:"小米500g",
            span:"28.00"
        },
        {
            src:"img/dadou.png",
            p:"大豆1000g",
            span:"99.00"
        },
        {
            src:"img/yumi.png",
            p:"玉米500g",
            span:"68.00"
        },
        {
            src:"img/xiaomai.png",
            p:"小麦500g",
            span:"46.00"
        },
        {
            src:"img/dami1.png",
            p:"大米400g",
            span:"29.00"
        },
        {
            src:"img/xiaomi.png",
            p:"小米500g",
            span:"28.00"
        }
    ];
})